"""Writes the oxblood favicon set.

The mark is a wine (#502d36) square with square corners and a paper (#f3eee5)
"E" from Libre Caslon Display, emboldened by STROKE_EM per side so its
hairlines survive at 16 to 32 px. The letter is not typed into the SVG: it is
rendered from the self-hosted font in Chromium, traced from the bitmap
(Moore-neighbour boundary trace, then Ramer-Douglas-Peucker simplification to
TOLERANCE px) and written as a single <path>, so the icons never depend on a
font being available. The glyph is centred on its ink box and scaled so the cap
height is CAP of the 64-unit square.

Outputs:
  public/favicon.svg, public/brand-mark.svg   the mark as SVG
  public/favicon.png (32x32)                  rendered from the SVG
  public/apple-touch-icon.png (180x180)       rendered from the SVG
Provenance is embedded in both PNGs with `impeccable embed-prompt`.

Run with --compare OUT.png to draw the traced path over the rendered glyph.
"""
import base64
import io
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from PIL import Image
from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / "public"
FONT = PUBLIC / "fonts/libre-caslon-display-400-latin.woff2"
IMPECCABLE = Path.home() / ".claude/plugins/cache/impeccable/impeccable/4.3.1/skills/impeccable/scripts/impeccable"
# On Windows, plain "bash" can resolve to WSL; prefer Git Bash, which the impeccable launcher expects.
BASH = next((b for b in (os.environ.get("BASH_EXE"), "C:/Program Files/Git/bin/bash.exe", shutil.which("bash")) if b and Path(b).exists()), "bash")

WINE = "#502d36"
PAPER = "#f3eee5"
RENDER = 1000       # px font size for the trace
STROKE_EM = 0.025   # emboldening added to each side of the outline, as a fraction of the font size
TOLERANCE = 1.4     # RDP tolerance in render px (about 0.09 of a unit at 64)
CAP = 0.56          # cap height as a fraction of the square

PROVENANCE = (
    "Enamplify favicon, generated by scripts/make_icons.py: a wine #502d36 square with a paper #f3eee5 "
    "capital E from Libre Caslon Display (SIL OFL), emboldened by 0.025em per side, rendered in Chromium, "
    "traced to an SVG path and rasterised. No generative model."
)


def font_uri() -> str:
    return "data:font/woff2;base64," + base64.b64encode(FONT.read_bytes()).decode("ascii")


def render_glyph(page) -> Image.Image:
    """The emboldened E, white on black, as a greyscale bitmap."""
    size = int(RENDER * 1.4)
    page.set_viewport_size({"width": size, "height": size})
    page.set_content(
        f"<!doctype html><style>@font-face{{font-family:D;src:url('{font_uri()}')}}"
        f"html,body{{margin:0;background:#000}}div{{width:{size}px;height:{size}px;display:grid;place-items:center;"
        f"font:400 {RENDER}px/1 D;color:#fff;-webkit-text-stroke:{RENDER * STROKE_EM * 2:.1f}px #fff;paint-order:stroke}}</style><div>E</div>"
    )
    page.evaluate("document.fonts.ready")
    page.wait_for_timeout(200)
    return Image.open(io.BytesIO(page.screenshot())).convert("L")


def trace(img: Image.Image):
    """Outer boundary of the single ink blob, clockwise, as pixel-corner points."""
    w, h = img.size
    px = img.load()
    ink = lambda x, y: 0 <= x < w and 0 <= y < h and px[x, y] >= 128
    start = next((x, y) for y in range(h) for x in range(w) if ink(x, y))
    # Moore-neighbour tracing over pixel centres
    dirs = [(1, 0), (1, 1), (0, 1), (-1, 1), (-1, 0), (-1, -1), (0, -1), (1, -1)]
    pts, cur, back = [start], start, 4  # came from the west
    while True:
        for i in range(8):
            d = (back + 1 + i) % 8
            nx, ny = cur[0] + dirs[d][0], cur[1] + dirs[d][1]
            if ink(nx, ny):
                back = (d + 4) % 8
                cur = (nx, ny)
                break
        if cur == start:
            break
        pts.append(cur)
        if len(pts) > 200000:
            raise SystemExit("trace did not close")
    return pts


def rdp(points, eps):
    def dist(p, a, b):
        (x, y), (x1, y1), (x2, y2) = p, a, b
        dx, dy = x2 - x1, y2 - y1
        if dx == dy == 0:
            return ((x - x1) ** 2 + (y - y1) ** 2) ** 0.5
        return abs(dy * x - dx * y + x2 * y1 - y2 * x1) / (dx * dx + dy * dy) ** 0.5
    stack, keep = [(0, len(points) - 1)], {0, len(points) - 1}
    while stack:
        i, j = stack.pop()
        best, idx = 0, None
        for k in range(i + 1, j):
            dd = dist(points[k], points[i], points[j])
            if dd > best:
                best, idx = dd, k
        if idx is not None and best > eps:
            keep.add(idx)
            stack += [(i, idx), (idx, j)]
    return [points[k] for k in sorted(keep)]


def e_path(page) -> str:
    img = render_glyph(page)
    bbox = img.point(lambda v: 255 if v >= 128 else 0).getbbox()
    pts = rdp(trace(img), TOLERANCE)
    x0, y0, x1, y1 = bbox
    scale = 64 * CAP / (y1 - y0)
    ox = (64 - (x1 - x0) * scale) / 2 + 0.6  # optical: the open right side reads light
    oy = (64 - (y1 - y0) * scale) / 2
    f = lambda v: f"{v:.2f}".rstrip("0").rstrip(".")
    coords = [(ox + (x - x0 + 0.5) * scale, oy + (y - y0 + 0.5) * scale) for x, y in pts]
    return "M" + "L".join(f"{f(x)} {f(y)}" for x, y in coords) + "Z"


def mark(path: str) -> str:
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">'
        f'<rect width="64" height="64" fill="{WINE}"/>'
        f'<path d="{path}" fill="{PAPER}"/>'
        "</svg>\n"
    )


def svg_uri(svg: str) -> str:
    return "data:image/svg+xml;base64," + base64.b64encode(svg.encode("utf-8")).decode("ascii")


def render_png(page, svg: str, size: int, out: Path) -> None:
    page.set_viewport_size({"width": size, "height": size})
    page.set_content(
        "<!doctype html><html><head><style>html,body{margin:0;background:transparent}"
        "img{display:block;width:100vw;height:100vh}</style></head>"
        f'<body><img src="{svg_uri(svg)}" alt=""></body></html>'
    )
    page.wait_for_function("document.images[0].complete")
    page.screenshot(path=str(out), omit_background=True)


def embed(path: Path) -> None:
    if not IMPECCABLE.exists():
        print("impeccable CLI not found; provenance not embedded in", path.name)
        return
    with tempfile.NamedTemporaryFile("w", suffix=".txt", delete=False, encoding="utf-8") as f:
        f.write(PROVENANCE)
        tmp = f.name
    try:
        r = subprocess.run([BASH, str(IMPECCABLE), "embed-prompt", str(path), "--prompt-file", tmp],
                           capture_output=True, text=True, encoding="utf-8")
        print(("embedded provenance in " + path.name) if r.returncode == 0 else ("embed-prompt failed: " + (r.stderr or r.stdout).strip()))
    finally:
        os.unlink(tmp)


def main() -> None:
    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page(device_scale_factor=1)
        path = e_path(page)
        svg = mark(path)
        for name in ("favicon.svg", "brand-mark.svg"):
            (PUBLIC / name).write_text(svg, encoding="utf-8", newline="\n")
            print(f"wrote public/{name} ({len(svg)} bytes)")
        for size, name in ((32, "favicon.png"), (180, "apple-touch-icon.png")):
            render_png(page, svg, size, PUBLIC / name)
            print(f"wrote public/{name}")
            embed(PUBLIC / name)
        if "--compare" in sys.argv:
            out = Path(sys.argv[sys.argv.index("--compare") + 1])
            glyph = render_glyph(page).convert("RGB")
            page.set_viewport_size({"width": 640, "height": 640})
            page.set_content(f'<body style="margin:0"><img src="{svg_uri(svg)}" width="640" height="640"></body>')
            page.wait_for_function("document.images[0].complete")
            Image.open(io.BytesIO(page.screenshot())).save(out)
            glyph.save(out.with_name(out.stem + "-glyph.png"))
            print(f"wrote {out}")
        browser.close()


if __name__ == "__main__":
    main()
